name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python_version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Setup mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Create the conda environment
      shell: bash -l {0}
      run: mamba install -q python=${{ matrix.python_version }} pip robotframework>=3.2 lunr nbformat>=4.4 flake8

    - name: Flake8
      shell: bash -l {0}
      run: |
        python -m flake8 robotframework_interpreter setup.py --ignore=E501
